// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Toffees.Glucose.Data;

namespace Toffees.Glucose.Migrations
{
    [DbContext(typeof(GlucoseDbContext))]
    [Migration("20171219215444_InitializeGlucoseEntity")]
    partial class InitializeGlucoseEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Toffees.Glucose.Data.Entities.Glucose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Data");

                    b.Property<DateTime>("PinchDateTime");

                    b.Property<string>("Tag");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Glucoses");
                });
#pragma warning restore 612, 618
        }
    }
}
